name: leoandjen_opal_v2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - expat=2.6.3=h5da7b33_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py312haa95532_0
  - python=3.12.7=h14ffc60_0
  - setuptools=75.1.0=py312haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wheel=0.44.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - asgiref==3.8.1
      - beautifulsoup4==4.12.3
      - boto3==1.35.54
      - botocore==1.35.54
      - bs4==0.0.2
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==43.0.3
      - cssbeautifier==1.15.1
      - django==5.1.10
      - django-debug-toolbar==4.4.6
      - django-environ==0.11.2
      - django-extensions==3.2.3
      - django-js-asset==2.2.0
      - django-storages==1.14.4
      - django-widget-tweaks==1.5.0
      - djhtml==3.0.8
      - djlint==1.35.4
      - editorconfig==0.12.4
      - html-tag-names==0.1.2
      - html-void-elements==0.1.0
      - idna==3.10
      - iniconfig==2.1.0
      - jellyfish==1.1.0
      - jmespath==1.0.1
      - jsbeautifier==1.15.1
      - json5==0.9.25
      - lxml==5.3.0
      - packaging==25.0
      - pathspec==0.12.1
      - pdfminer-six==20250327
      - pdfplumber==0.11.6
      - pillow==11.0.0
      - pluggy==1.6.0
      - psycopg2-binary==2.9.10
      - pycparser==2.22
      - pyflame==0.3.2
      - pypdfium2==4.30.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - s3transfer==0.10.3
      - six==1.16.0
      - soupsieve==2.6
      - sqlparse==0.5.1
      - tomli==2.0.2
      - tqdm==4.66.6
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - us==3.2.0
prefix: C:\Users\leo\miniconda3.12\envs\leoandjen_opal_v2
